/**
 * `rosetta types <map> -o <out.d.ts>` — emit a TypeScript declaration stub
 * for a map's REAL names.
 *
 * A hook author writes against real (unobfuscated) names through
 * `rosetta.use(...)` / `rosetta.hook(...)`. Those names are stringly-typed
 * at the call site, so a typo (`requestTickett`) is only caught at runtime.
 * `types` turns a map into a `.d.ts` of string-literal unions so an editor
 * can offer autocompletion and a build can flag a stale name.
 *
 * The emitted module declares:
 *   - `RosettaClassName` — a union of every real class name.
 *   - `RosettaMethodName` — a union of `ClassName.methodName` for every
 *     real method (the `rosetta.hook(...)` tier-1 target shape).
 *   - `RosettaFieldName` — a union of `ClassName.fieldName`.
 *   - `RosettaRealNames` — an interface mapping each class to its method
 *     and field name unions, for richer per-class typing.
 *
 * This is purely derived from the map's KEYS (the real names) — it never
 * emits obfuscated names (those rotate; that is the whole point) and never
 * reads an APK. Output is deterministic: names are sorted.
 */

import { RosettaError } from '../../src/errors.js';
import type { RosettaMap } from '../../src/types/map.js';
import type { CommandIo, FsLike } from './io.js';
import { writeNew } from './io.js';
import { loadMap } from './validate.js';
import { parseArgs, type ArgSpec } from './args.js';

/** Parsed argument shape for `types`. */
export interface TypesOptions {
    /** Input map path. */
    inputPath: string;
    /** Where to write the `.d.ts` stub. */
    outputPath: string;
    /** Overwrite an existing output file. */
    force: boolean;
}

/** Option grammar for `types`: one positional + `-o`, `--force`. */
const TYPES_SPEC: ArgSpec = {
    options: [
        { name: 'output', aliases: ['-o', '--output'], takesValue: true },
        { name: 'force', aliases: ['--force', '-f'], takesValue: false },
    ],
};

/** Parse argv → TypesOptions. */
export function parseTypesArgs(argv: readonly string[]): TypesOptions {
    const { positionals, values, flags } = parseArgs(argv, TYPES_SPEC);
    if (positionals.length !== 1) {
        throw new RosettaError(
            `types requires exactly one positional arg: <map> (got ${positionals.length})`,
        );
    }
    if (values.output === undefined) {
        throw new RosettaError('types requires -o <out.d.ts>');
    }
    return {
        inputPath: positionals[0] as string,
        outputPath: values.output,
        force: flags.force ?? false,
    };
}

/** Render a string-literal union (or `never` when empty). */
function unionOf(names: readonly string[]): string {
    if (names.length === 0) return 'never';
    return names.map((n) => `'${n}'`).join(' | ');
}

/** A class plus its sorted method/field real names. */
interface ClassNames {
    className: string;
    methods: string[];
    fields: string[];
}

/** Extract the sorted real-name structure from a map. */
export function collectNames(map: RosettaMap): ClassNames[] {
    return Object.keys(map.classes)
        .sort()
        .map((className) => {
            const entry = map.classes[className];
            return {
                className,
                methods: Object.keys(entry?.methods ?? {}).sort(),
                fields: Object.keys(entry?.fields ?? {}).sort(),
            };
        });
}

/**
 * Render the full `.d.ts` text for a map. Deterministic: every union is
 * sorted, so the same map always produces byte-identical output. Ends with
 * a trailing newline (POSIX / Prettier convention).
 */
export function renderTypes(map: RosettaMap): string {
    const classes = collectNames(map);
    const classUnion = unionOf(classes.map((c) => c.className));
    const methodUnion = unionOf(
        classes.flatMap((c) => c.methods.map((m) => `${c.className}.${m}`)),
    );
    const fieldUnion = unionOf(classes.flatMap((c) => c.fields.map((f) => `${c.className}.${f}`)));

    const lines: string[] = [];
    lines.push('/**');
    lines.push(` * Real-name type stubs for ${map.app}@${map.version}`);
    lines.push(` * (version_code ${map.version_code}). Generated by \`rosetta types\`.`);
    lines.push(' *');
    lines.push(' * Do not edit by hand — re-run `rosetta types` when the map changes.');
    lines.push(' * Contains only REAL names (never obfuscated names, which rotate).');
    lines.push(' */');
    lines.push('');
    lines.push('/** Every real (unobfuscated) class name in the map. */');
    lines.push(`export type RosettaClassName = ${classUnion};`);
    lines.push('');
    lines.push('/** Every real `Class.method` tier-1 hook target in the map. */');
    lines.push(`export type RosettaMethodName = ${methodUnion};`);
    lines.push('');
    lines.push('/** Every real `Class.field` accessor target in the map. */');
    lines.push(`export type RosettaFieldName = ${fieldUnion};`);
    lines.push('');
    lines.push('/** Per-class real method/field names, for richer typing. */');
    lines.push('export interface RosettaRealNames {');
    for (const c of classes) {
        lines.push(`    ${JSON.stringify(c.className)}: {`);
        lines.push(`        methods: ${unionOf(c.methods)};`);
        lines.push(`        fields: ${unionOf(c.fields)};`);
        lines.push('    };');
    }
    lines.push('}');
    return `${lines.join('\n')}\n`;
}

/**
 * Core of `rosetta types`: load the map, render the stub, write it. Returns
 * the output path. Separated from the printing wrapper for unit testing.
 */
export async function typesFile(argv: readonly string[], fs: FsLike): Promise<string> {
    const opts = parseTypesArgs(argv);
    const map = await loadMap(opts.inputPath, fs);
    await writeNew(fs, opts.outputPath, renderTypes(map), { force: opts.force });
    return opts.outputPath;
}

/**
 * Execute `rosetta types` under the shared command contract: render the
 * `.d.ts` and return the success message.
 */
export async function runTypes(argv: readonly string[], io: CommandIo): Promise<string> {
    const out = await typesFile(argv, io.fs);
    return `wrote ${out}`;
}
