/**
 * Pure `.d.ts` renderer over one loaded {@link RosettaMap}.
 *
 * The emitted module declares:
 *   - `RosettaClassName` — a union of every real class name.
 *   - `RosettaMethodName` — a union of `ClassName.methodName` for every real
 *     method (the `rosetta.hook(...)` tier-1 target shape).
 *   - `RosettaFieldName` — a union of `ClassName.fieldName`.
 *   - `RosettaRealNames` — an interface mapping each class to its method and
 *     field name unions, for richer per-class typing.
 *
 * Purely derived from the map's KEYS (the real names) — it never emits
 * obfuscated names (those rotate; that is the whole point) and never reads an
 * APK. Output is deterministic: names are sorted.
 *
 * All emitted string literals go through `JSON.stringify` so a name
 * containing a quote or backslash (the schema permits any non-empty `classes`
 * key) renders as a valid, fully-escaped double-quoted literal rather than a
 * broken single-quoted one; and the JSDoc header sanitizes a comment
 * terminator out of the interpolated `app`/`version` so a hostile `version`
 * cannot break out of the generated comment block.
 */

import type { RosettaMap } from '../types/map.js';

/**
 * Render a string-literal union (or `never` when empty). Each literal is
 * emitted with `JSON.stringify` so quotes/backslashes in a (schema-legal)
 * name are double-quoted and fully escaped — single-quoting them raw produced
 * invalid TypeScript.
 */
function unionOf(names: readonly string[]): string {
    if (names.length === 0) return 'never';
    return names.map((n) => JSON.stringify(n)).join(' | ');
}

/**
 * Neutralize a block-comment terminator sequence in text interpolated into the
 * generated JSDoc header so it cannot close the comment early. A `version`
 * carrying that sequence is schema-legal; left raw it would break out of the
 * header comment and corrupt the emitted `.d.ts`. The two terminator
 * characters are split by a space so the rendered text stays readable.
 */
function sanitizeForBlockComment(text: string): string {
    return text.replace(/\*\//g, '* /');
}

/** A class plus its sorted method/field real names. */
export interface ClassNames {
    className: string;
    methods: string[];
    fields: string[];
}

/** Extract the sorted real-name structure from a map. */
export function collectNames(map: RosettaMap): ClassNames[] {
    return Object.keys(map.classes)
        .sort()
        .map((className) => {
            const entry = map.classes[className];
            return {
                className,
                methods: Object.keys(entry?.methods ?? {}).sort(),
                fields: Object.keys(entry?.fields ?? {}).sort(),
            };
        });
}

/**
 * Render the full `.d.ts` text for a map. Deterministic: every union is
 * sorted, so the same map always produces byte-identical output. Ends with a
 * trailing newline (POSIX / Prettier convention).
 */
export function renderTypes(map: RosettaMap): string {
    const classes = collectNames(map);
    const classUnion = unionOf(classes.map((c) => c.className));
    const methodUnion = unionOf(
        classes.flatMap((c) => c.methods.map((m) => `${c.className}.${m}`)),
    );
    const fieldUnion = unionOf(classes.flatMap((c) => c.fields.map((f) => `${c.className}.${f}`)));
    const app = sanitizeForBlockComment(map.app);
    const version = sanitizeForBlockComment(map.version);

    const lines: string[] = [];
    lines.push('/**');
    lines.push(` * Real-name type stubs for ${app}@${version}`);
    lines.push(` * (version_code ${map.version_code}). Generated by \`rosetta types\`.`);
    lines.push(' *');
    lines.push(' * Do not edit by hand — re-run `rosetta types` when the map changes.');
    lines.push(' * Contains only REAL names (never obfuscated names, which rotate).');
    lines.push(' */');
    lines.push('');
    lines.push('/** Every real (unobfuscated) class name in the map. */');
    lines.push(`export type RosettaClassName = ${classUnion};`);
    lines.push('');
    lines.push('/** Every real `Class.method` tier-1 hook target in the map. */');
    lines.push(`export type RosettaMethodName = ${methodUnion};`);
    lines.push('');
    lines.push('/** Every real `Class.field` accessor target in the map. */');
    lines.push(`export type RosettaFieldName = ${fieldUnion};`);
    lines.push('');
    lines.push('/** Per-class real method/field names, for richer typing. */');
    lines.push('export interface RosettaRealNames {');
    for (const c of classes) {
        lines.push(`    ${JSON.stringify(c.className)}: {`);
        lines.push(`        methods: ${unionOf(c.methods)};`);
        lines.push(`        fields: ${unionOf(c.fields)};`);
        lines.push('    };');
    }
    lines.push('}');
    return `${lines.join('\n')}\n`;
}
